(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(amx-history-length 10)
 '(amx-save-file "/home/jpprime/.emacs.d/.cache/amx-items")
 '(auto-revert-check-vc-info t)
 '(coq-compile-before-require t t)
 '(create-lockfiles t)
 '(debug-on-error nil)
 '(doc-view-continuous t t)
 '(doc-view-resolution 200 t)
 '(dumb-jump-mode-selector (quote ivy) t)
 '(dumb-jump-prefer-searcher (quote rg))
 '(evil-search-module (quote evil-search))
 '(evil-shift-width 4)
 '(indent-tabs-mode nil)
 '(ivy-count-format "%d/%d ")
 '(ivy-height 16)
 '(ivy-initial-inputs-alist nil)
 '(ivy-use-virtual-buffers t)
 '(ivy-wrap t)
 '(magit-completing-read-function (quote ivy-completing-read))
 '(magit-diff-arguments (quote ("--histogram")) t)
 '(magit-display-buffer-function (quote magit-display-buffer-traditional))
 '(magit-ediff-dwim-show-on-hunks t)
 '(magit-merge-arguments (quote ("--no-ff")) t)
 '(magit-section-show-child-couno t t)
 '(magit-todos-fontify-org nil)
 '(magit-todos-scanner (quote magit-todos--scan-with-rg))
 '(org-agenda-files (quote ("~/docs/org/inbox.org")))
 '(org-directory "/home/jpprime/docs/org")
 '(org-indent-indentation-per-level 0 t)
 '(org-src-fontify-natively t)
 '(org-startup-indented nil)
 '(origami-fold-style (quote triple-braces) t)
 '(package-selected-packages
   (quote
    (gitignore-mode crontab-mode yasnippet-snippets yasnippet-classic-snippets which-key vimrc-mode treemacs-projectile rich-minority proof-general pdf-tools page-break-lines ox-pandoc markdown-mode magit-todos ivy-yasnippet ivy-hydra ivy-bibtex helpful evil-surround evil-org evil-numbers evil-matchit evil-magit esh-help dumb-jump counsel-tramp counsel-projectile company-coq auctex amx aggressive-indent)))
 '(pdf-view-midnight-colors (quote ("#ffffff" . "#000000")) t)
 '(pdf-view-resize-factor 1.1 t)
 '(projectile-cache-file "~/.emacs.d/.cache/projectile.cache")
 '(projectile-completion-system (quote ivy))
 '(projectile-enable-caching t)
 '(projectile-generic-command
   "ag -0 -l --nocolor --ignore-dir=node_modules --ignore-dir=dist --ignore-dir=target --ignore-dir=.cache --ignore-dir=elpa --ignore-dir=.idea --ignore-dir=.ensime_cache --ignore-dir=.eunit --ignore-dir=.git --ignore-dir=.hg --ignore-dir=.fslckout --ignore-dir=_FOSSIL_ --ignore-dir=.bzr --ignore-dir=_darcs --ignore-dir=.tox --ignore-dir=.svn --ignore-dir=.stack-work")
 '(projectile-indexing-method (quote alien))
 '(projectile-known-projects-file "~/.emacs.d/.cache/projectile-bookmarks.eld")
 '(projectile-project-compilation-cmd "" t)
 '(projectile-project-run-cmd "" t)
 '(proof-electric-terminator-enable t t)
 '(proof-script-fly-past-comments t t)
 '(proof-splash-enable nil t)
 '(proof-strict-read-only (quote retract) t)
 '(proof-three-window-mode-policy (quote smart) t)
 '(smerge-command-prefix "n" t)
 '(tab-width 8)
 '(treemacs-no-png-images nil t)
 '(undo-tree-auto-save-history t)
 '(undo-tree-enable-undo-in-region nil)
 '(undo-tree-history-directory-alist (quote (("." . "~/.emacs.d/.cache/undo/"))))
 '(undo-tree-visualizer-diff t)
 '(undo-tree-visualizer-timestamps t)
 '(vc-follow-symlinks t)
 '(vc-make-backup-files t)
 '(which-key-allow-evil-operators t)
 '(which-key-idle-delay 0.2)
 '(which-key-min-display-lines 3)
 '(yas-also-auto-indent-first-line t)
 '(yas-fallback-behaviour (quote return-nil) t))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
